CREATE OR REPLACE TABLE `{{ params.dwh_dataset }}.D_TIME` AS

SELECT
  ARRIVAL_DATE DATE,
  EXTRACT(DAY FROM ARRIVAL_DATE) AS DAY,
  EXTRACT(MONTH FROM ARRIVAL_DATE) AS MONTH,
  EXTRACT(YEAR FROM ARRIVAL_DATE) AS YEAR,
  EXTRACT(QUARTER FROM ARRIVAL_DATE) AS QUARTER,
  EXTRACT(DAYOFWEEK FROM ARRIVAL_DATE) AS DAYOFWEEK,
  EXTRACT(WEEK FROM ARRIVAL_DATE) AS WEEKOFYEAR
FROM (
  SELECT
    DISTINCT ARRIVAL_DATE
  FROM
    `{{ params.project_id }}.{{ params.dwh_dataset }}.F_IMMIGRATION_DATA`
  UNION DISTINCT
  SELECT
    DISTINCT DEPARTURE_DATE
  FROM
    `{{ params.project_id }}.{{ params.dwh_dataset }}.F_IMMIGRATION_DATA`)

 WHERE ARRIVAL_DATE IS NOT NULL
